# -*- coding: utf-8 -*-
# ─────────────────────────────────────────────
#  IV CALCULATOR DATA  (Source: paldb.cc/en/Iv_Calc)
#  Keyed by Pal Blueprint Code (same as _PW_PALS pal_id)
#  Fields: id, name, Hp, ShotAttack, Defense
# ─────────────────────────────────────────────
IV_PAL_DATA = {
    'YakushimaMonster001': {'id': '', 'name': 'Green Slime', 'Hp': 65, 'ShotAttack': 70, 'Defense': 80},
    'YakushimaMonster001_Blue': {'id': '', 'name': 'Blue Slime', 'Hp': 70, 'ShotAttack': 70, 'Defense': 80},
    'YakushimaMonster001_Red': {'id': '', 'name': 'Red Slime', 'Hp': 70, 'ShotAttack': 75, 'Defense': 85},
    'YakushimaMonster001_Purple': {'id': '', 'name': 'Purple Slime', 'Hp': 75, 'ShotAttack': 70, 'Defense': 80},
    'YakushimaMonster001_Pink': {'id': '', 'name': 'Illuminant Slime', 'Hp': 80, 'ShotAttack': 75, 'Defense': 85},
    'YakushimaMonster001_Rainbow': {'id': '', 'name': 'Rainbow Slime', 'Hp': 105, 'ShotAttack': 95, 'Defense': 105},
    'YakushimaMonster002': {'id': '', 'name': 'Enchanted Sword', 'Hp': 95, 'ShotAttack': 105, 'Defense': 90},
    'YakushimaMonster003': {'id': '', 'name': 'Cave Bat', 'Hp': 65, 'ShotAttack': 75, 'Defense': 80},
    'YakushimaMonster003_Purple': {'id': '', 'name': 'Illuminant Bat', 'Hp': 80, 'ShotAttack': 80, 'Defense': 95},
    'YakushimaBoss001': {'id': '', 'name': 'Eye of Cthulhu', 'Hp': 110, 'ShotAttack': 105, 'Defense': 95},
    'YakushimaBoss001_Small': {'id': '', 'name': 'Demon Eye', 'Hp': 105, 'ShotAttack': 110, 'Defense': 95},
    'SheepBall': {'id': '1', 'name': 'Lamball', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'PinkCat': {'id': '2', 'name': 'Cattiva', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'ChickenPal': {'id': '3', 'name': 'Chikipi', 'Hp': 60, 'ShotAttack': 60, 'Defense': 60},
    'Carbunclo': {'id': '4', 'name': 'Lifmunk', 'Hp': 75, 'ShotAttack': 70, 'Defense': 70},
    'Kitsunebi': {'id': '5', 'name': 'Foxparks', 'Hp': 65, 'ShotAttack': 75, 'Defense': 70},
    'Kitsunebi_Ice': {'id': '5B', 'name': 'Foxparks Cryst', 'Hp': 65, 'ShotAttack': 80, 'Defense': 70},
    'BluePlatypus': {'id': '6', 'name': 'Fuack', 'Hp': 60, 'ShotAttack': 80, 'Defense': 60},
    'BluePlatypus_Fire': {'id': '6B', 'name': 'Fuack Ignis', 'Hp': 60, 'ShotAttack': 85, 'Defense': 60},
    'ElecCat': {'id': '7', 'name': 'Sparkit', 'Hp': 60, 'ShotAttack': 75, 'Defense': 70},
    'Monkey': {'id': '8', 'name': 'Tanzee', 'Hp': 80, 'ShotAttack': 70, 'Defense': 70},
    'FlameBambi': {'id': '9', 'name': 'Rooby', 'Hp': 75, 'ShotAttack': 70, 'Defense': 75},
    'Penguin': {'id': '10', 'name': 'Pengullet', 'Hp': 70, 'ShotAttack': 75, 'Defense': 70},
    'Penguin_Electric': {'id': '10B', 'name': 'Pengullet Lux', 'Hp': 70, 'ShotAttack': 80, 'Defense': 70},
    'CaptainPenguin': {'id': '11', 'name': 'Penking', 'Hp': 95, 'ShotAttack': 95, 'Defense': 95},
    'CaptainPenguin_Black': {'id': '11B', 'name': 'Penking Lux', 'Hp': 100, 'ShotAttack': 100, 'Defense': 100},
    'Hedgehog': {'id': '12', 'name': 'Jolthog', 'Hp': 70, 'ShotAttack': 75, 'Defense': 70},
    'Hedgehog_Ice': {'id': '12B', 'name': 'Jolthog Cryst', 'Hp': 70, 'ShotAttack': 75, 'Defense': 80},
    'PlantSlime': {'id': '13', 'name': 'Gumoss', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'CuteFox': {'id': '14', 'name': 'Vixy', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'WizardOwl': {'id': '15', 'name': 'Hoocrates', 'Hp': 70, 'ShotAttack': 70, 'Defense': 80},
    'Ganesha': {'id': '16', 'name': 'Teafant', 'Hp': 70, 'ShotAttack': 60, 'Defense': 70},
    'NegativeKoala': {'id': '17', 'name': 'Depresso', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'WoolFox': {'id': '18', 'name': 'Cremis', 'Hp': 70, 'ShotAttack': 70, 'Defense': 75},
    'DreamDemon': {'id': '19', 'name': 'Daedream', 'Hp': 70, 'ShotAttack': 75, 'Defense': 60},
    'Boar': {'id': '20', 'name': 'Rushoar', 'Hp': 80, 'ShotAttack': 70, 'Defense': 70},
    'NightFox': {'id': '21', 'name': 'Nox', 'Hp': 75, 'ShotAttack': 85, 'Defense': 70},
    'CuteMole': {'id': '22', 'name': 'Fuddler', 'Hp': 65, 'ShotAttack': 80, 'Defense': 50},
    'NegativeOctopus': {'id': '23', 'name': 'Killamari', 'Hp': 60, 'ShotAttack': 60, 'Defense': 70},
    'NegativeOctopus_Neutral': {'id': '23B', 'name': 'Killamari Primo', 'Hp': 70, 'ShotAttack': 60, 'Defense': 70},
    'Bastet': {'id': '24', 'name': 'Mau', 'Hp': 70, 'ShotAttack': 60, 'Defense': 70},
    'Bastet_Ice': {'id': '24B', 'name': 'Mau Cryst', 'Hp': 70, 'ShotAttack': 65, 'Defense': 70},
    'FlyingManta': {'id': '25', 'name': 'Celaray', 'Hp': 80, 'ShotAttack': 70, 'Defense': 80},
    'FlyingManta_Thunder': {'id': '25B', 'name': 'Celaray Lux', 'Hp': 80, 'ShotAttack': 75, 'Defense': 80},
    'Garm': {'id': '26', 'name': 'Direhowl', 'Hp': 80, 'ShotAttack': 90, 'Defense': 75},
    'ColorfulBird': {'id': '27', 'name': 'Tocotoco', 'Hp': 60, 'ShotAttack': 75, 'Defense': 70},
    'FlowerRabbit': {'id': '28', 'name': 'Flopie', 'Hp': 75, 'ShotAttack': 65, 'Defense': 70},
    'CowPal': {'id': '29', 'name': 'Mozzarina', 'Hp': 90, 'ShotAttack': 50, 'Defense': 80},
    'LittleBriarRose': {'id': '30', 'name': 'Bristla', 'Hp': 80, 'ShotAttack': 80, 'Defense': 80},
    'SharkKid': {'id': '31', 'name': 'Gobfin', 'Hp': 90, 'ShotAttack': 90, 'Defense': 75},
    'SharkKid_Fire': {'id': '31B', 'name': 'Gobfin Ignis', 'Hp': 90, 'ShotAttack': 90, 'Defense': 75},
    'WindChimes': {'id': '32', 'name': 'Hangyu', 'Hp': 80, 'ShotAttack': 70, 'Defense': 70},
    'WindChimes_Ice': {'id': '32B', 'name': 'Hangyu Cryst', 'Hp': 80, 'ShotAttack': 80, 'Defense': 70},
    'GrassPanda': {'id': '33', 'name': 'Mossanda', 'Hp': 100, 'ShotAttack': 90, 'Defense': 90},
    'GrassPanda_Electric': {'id': '33B', 'name': 'Mossanda Lux', 'Hp': 100, 'ShotAttack': 100, 'Defense': 100},
    'SweetsSheep': {'id': '34', 'name': 'Woolipop', 'Hp': 70, 'ShotAttack': 70, 'Defense': 90},
    'BerryGoat': {'id': '35', 'name': 'Caprity', 'Hp': 100, 'ShotAttack': 70, 'Defense': 90},
    'BerryGoat_Dark': {'id': '35B', 'name': 'Caprity Noct', 'Hp': 100, 'ShotAttack': 75, 'Defense': 90},
    'Alpaca': {'id': '36', 'name': 'Melpaca', 'Hp': 90, 'ShotAttack': 75, 'Defense': 90},
    'Deer': {'id': '37', 'name': 'Eikthyrdeer', 'Hp': 95, 'ShotAttack': 80, 'Defense': 80},
    'Deer_Ground': {'id': '37B', 'name': 'Eikthyrdeer Terra', 'Hp': 95, 'ShotAttack': 80, 'Defense': 80},
    'HawkBird': {'id': '38', 'name': 'Nitewing', 'Hp': 100, 'ShotAttack': 95, 'Defense': 80},
    'PinkRabbit': {'id': '39', 'name': 'Ribbuny', 'Hp': 75, 'ShotAttack': 65, 'Defense': 70},
    'PinkRabbit_Grass': {'id': '39B', 'name': 'Ribbuny Botan', 'Hp': 80, 'ShotAttack': 65, 'Defense': 70},
    'Baphomet': {'id': '40', 'name': 'Incineram', 'Hp': 95, 'ShotAttack': 100, 'Defense': 85},
    'Baphomet_Dark': {'id': '40B', 'name': 'Incineram Noct', 'Hp': 95, 'ShotAttack': 105, 'Defense': 85},
    'CuteButterfly': {'id': '41', 'name': 'Cinnamoth', 'Hp': 70, 'ShotAttack': 80, 'Defense': 80},
    'FlameBuffalo': {'id': '42', 'name': 'Arsox', 'Hp': 85, 'ShotAttack': 95, 'Defense': 95},
    'LazyCatfish': {'id': '43', 'name': 'Dumud', 'Hp': 100, 'ShotAttack': 70, 'Defense': 95},
    'LazyCatfish_Gold': {'id': '43B', 'name': 'Dumud Gild', 'Hp': 105, 'ShotAttack': 75, 'Defense': 100},
    'DarkCrow': {'id': '44', 'name': 'Cawgnito', 'Hp': 75, 'ShotAttack': 95, 'Defense': 80},
    'LizardMan': {'id': '45', 'name': 'Leezpunk', 'Hp': 80, 'ShotAttack': 80, 'Defense': 50},
    'LizardMan_Fire': {'id': '45B', 'name': 'Leezpunk Ignis', 'Hp': 80, 'ShotAttack': 80, 'Defense': 50},
    'Werewolf': {'id': '46', 'name': 'Loupmoon', 'Hp': 80, 'ShotAttack': 100, 'Defense': 80},
    'Werewolf_Ice': {'id': '46B', 'name': 'Loupmoon Cryst', 'Hp': 80, 'ShotAttack': 105, 'Defense': 80},
    'Eagle': {'id': '47', 'name': 'Galeclaw', 'Hp': 75, 'ShotAttack': 85, 'Defense': 60},
    'RobinHood': {'id': '48', 'name': 'Robinquill', 'Hp': 90, 'ShotAttack': 105, 'Defense': 80},
    'RobinHood_Ground': {'id': '48B', 'name': 'Robinquill Terra', 'Hp': 90, 'ShotAttack': 105, 'Defense': 80},
    'Gorilla': {'id': '49', 'name': 'Gorirat', 'Hp': 90, 'ShotAttack': 95, 'Defense': 90},
    'Gorilla_Ground': {'id': '49B', 'name': 'Gorirat Terra', 'Hp': 90, 'ShotAttack': 100, 'Defense': 90},
    'SoldierBee': {'id': '50', 'name': 'Beegarde', 'Hp': 80, 'ShotAttack': 90, 'Defense': 90},
    'QueenBee': {'id': '51', 'name': 'Elizabee', 'Hp': 90, 'ShotAttack': 105, 'Defense': 100},
    'NaughtyCat': {'id': '52', 'name': 'Grintale', 'Hp': 110, 'ShotAttack': 80, 'Defense': 80},
    'MopBaby': {'id': '53', 'name': 'Swee', 'Hp': 60, 'ShotAttack': 60, 'Defense': 60},
    'MopKing': {'id': '54', 'name': 'Sweepa', 'Hp': 100, 'ShotAttack': 90, 'Defense': 90},
    'WeaselDragon': {'id': '55', 'name': 'Chillet', 'Hp': 90, 'ShotAttack': 80, 'Defense': 80},
    'WeaselDragon_Fire': {'id': '55B', 'name': 'Chillet Ignis', 'Hp': 90, 'ShotAttack': 85, 'Defense': 80},
    'Kirin': {'id': '56', 'name': 'Univolt', 'Hp': 80, 'ShotAttack': 105, 'Defense': 105},
    'IceFox': {'id': '57', 'name': 'Foxcicle', 'Hp': 90, 'ShotAttack': 95, 'Defense': 105},
    'FireKirin': {'id': '58', 'name': 'Pyrin', 'Hp': 100, 'ShotAttack': 95, 'Defense': 90},
    'FireKirin_Dark': {'id': '58B', 'name': 'Pyrin Noct', 'Hp': 100, 'ShotAttack': 95, 'Defense': 90},
    'IceDeer': {'id': '59', 'name': 'Reindrix', 'Hp': 100, 'ShotAttack': 85, 'Defense': 110},
    'ThunderDog': {'id': '60', 'name': 'Rayhound', 'Hp': 90, 'ShotAttack': 100, 'Defense': 80},
    'AmaterasuWolf': {'id': '61', 'name': 'Kitsun', 'Hp': 100, 'ShotAttack': 115, 'Defense': 100},
    'AmaterasuWolf_Dark': {'id': '61B', 'name': 'Kitsun Noct', 'Hp': 100, 'ShotAttack': 115, 'Defense': 105},
    'RaijinDaughter': {'id': '62', 'name': 'Dazzi', 'Hp': 70, 'ShotAttack': 80, 'Defense': 70},
    'RaijinDaughter_Water': {'id': '62B', 'name': 'Dazzi Noct', 'Hp': 70, 'ShotAttack': 80, 'Defense': 75},
    'Mutant': {'id': '63', 'name': 'Lunaris', 'Hp': 90, 'ShotAttack': 100, 'Defense': 90},
    'FlowerDinosaur': {'id': '64', 'name': 'Dinossom', 'Hp': 110, 'ShotAttack': 85, 'Defense': 90},
    'FlowerDinosaur_Electric': {'id': '64B', 'name': 'Dinossom Lux', 'Hp': 110, 'ShotAttack': 90, 'Defense': 90},
    'Serpent': {'id': '65', 'name': 'Surfent', 'Hp': 90, 'ShotAttack': 90, 'Defense': 80},
    'Serpent_Ground': {'id': '65B', 'name': 'Surfent Terra', 'Hp': 90, 'ShotAttack': 90, 'Defense': 100},
    'GhostBeast': {'id': '66', 'name': 'Maraith', 'Hp': 75, 'ShotAttack': 105, 'Defense': 80},
    'DrillGame': {'id': '67', 'name': 'Digtoise', 'Hp': 80, 'ShotAttack': 95, 'Defense': 120},
    'CatBat': {'id': '68', 'name': 'Tombat', 'Hp': 95, 'ShotAttack': 95, 'Defense': 80},
    'PinkLizard': {'id': '69', 'name': 'Lovander', 'Hp': 120, 'ShotAttack': 70, 'Defense': 70},
    'LavaGirl': {'id': '70', 'name': 'Flambelle', 'Hp': 60, 'ShotAttack': 70, 'Defense': 80},
    'BirdDragon': {'id': '71', 'name': 'Vanwyrm', 'Hp': 90, 'ShotAttack': 115, 'Defense': 90},
    'BirdDragon_Ice': {'id': '71B', 'name': 'Vanwyrm Cryst', 'Hp': 90, 'ShotAttack': 120, 'Defense': 95},
    'Ronin': {'id': '72', 'name': 'Bushi', 'Hp': 80, 'ShotAttack': 125, 'Defense': 80},
    'Ronin_Dark': {'id': '72B', 'name': 'Bushi Noct', 'Hp': 80, 'ShotAttack': 130, 'Defense': 80},
    'ThunderBird': {'id': '73', 'name': 'Beakon', 'Hp': 105, 'ShotAttack': 115, 'Defense': 80},
    'RedArmorBird': {'id': '74', 'name': 'Ragnahawk', 'Hp': 95, 'ShotAttack': 105, 'Defense': 120},
    'CatMage': {'id': '75', 'name': 'Katress', 'Hp': 90, 'ShotAttack': 105, 'Defense': 90},
    'CatMage_Fire': {'id': '75B', 'name': 'Katress Ignis', 'Hp': 95, 'ShotAttack': 105, 'Defense': 90},
    'FoxMage': {'id': '76', 'name': 'Wixen', 'Hp': 90, 'ShotAttack': 110, 'Defense': 80},
    'FoxMage_Dark': {'id': '76B', 'name': 'Wixen Noct', 'Hp': 90, 'ShotAttack': 110, 'Defense': 85},
    'GrassRabbitMan': {'id': '77', 'name': 'Verdash', 'Hp': 90, 'ShotAttack': 115, 'Defense': 90},
    'VioletFairy': {'id': '78', 'name': 'Vaelet', 'Hp': 100, 'ShotAttack': 100, 'Defense': 120},
    'WhiteMoth': {'id': '79', 'name': 'Sibelyx', 'Hp': 110, 'ShotAttack': 90, 'Defense': 100},
    'FairyDragon': {'id': '80', 'name': 'Elphidran', 'Hp': 110, 'ShotAttack': 80, 'Defense': 90},
    'FairyDragon_Water': {'id': '80B', 'name': 'Elphidran Aqua', 'Hp': 115, 'ShotAttack': 80, 'Defense': 95},
    'Kelpie': {'id': '81', 'name': 'Kelpsea', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'Kelpie_Fire': {'id': '81B', 'name': 'Kelpsea Ignis', 'Hp': 70, 'ShotAttack': 70, 'Defense': 70},
    'BlueDragon': {'id': '82', 'name': 'Azurobe', 'Hp': 110, 'ShotAttack': 100, 'Defense': 100},
    'BlueDragon_Ice': {'id': '82B', 'name': 'Azurobe Cryst', 'Hp': 115, 'ShotAttack': 105, 'Defense': 105},
    'WhiteTiger': {'id': '83', 'name': 'Cryolinx', 'Hp': 100, 'ShotAttack': 100, 'Defense': 110},
    'WhiteTiger_Ground': {'id': '83B', 'name': 'Cryolinx Terra', 'Hp': 100, 'ShotAttack': 105, 'Defense': 110},
    'Manticore': {'id': '84', 'name': 'Blazehowl', 'Hp': 105, 'ShotAttack': 110, 'Defense': 80},
    'Manticore_Dark': {'id': '84B', 'name': 'Blazehowl Noct', 'Hp': 105, 'ShotAttack': 115, 'Defense': 80},
    'LazyDragon': {'id': '85', 'name': 'Relaxaurus', 'Hp': 110, 'ShotAttack': 100, 'Defense': 70},
    'LazyDragon_Electric': {'id': '85B', 'name': 'Relaxaurus Lux', 'Hp': 110, 'ShotAttack': 110, 'Defense': 75},
    'SakuraSaurus': {'id': '86', 'name': 'Broncherry', 'Hp': 120, 'ShotAttack': 90, 'Defense': 100},
    'SakuraSaurus_Water': {'id': '86B', 'name': 'Broncherry Aqua', 'Hp': 120, 'ShotAttack': 95, 'Defense': 100},
    'FlowerDoll': {'id': '87', 'name': 'Petallia', 'Hp': 100, 'ShotAttack': 95, 'Defense': 100},
    'VolcanicMonster': {'id': '88', 'name': 'Reptyro', 'Hp': 110, 'ShotAttack': 105, 'Defense': 120},
    'VolcanicMonster_Ice': {'id': '88B', 'name': 'Reptyro Cryst', 'Hp': 110, 'ShotAttack': 105, 'Defense': 130},
    'KingAlpaca': {'id': '89', 'name': 'Kingpaca', 'Hp': 120, 'ShotAttack': 85, 'Defense': 90},
    'KingAlpaca_Ice': {'id': '89B', 'name': 'Kingpaca Cryst', 'Hp': 120, 'ShotAttack': 85, 'Defense': 90},
    'GrassMammoth': {'id': '90', 'name': 'Mammorest', 'Hp': 150, 'ShotAttack': 85, 'Defense': 90},
    'GrassMammoth_Ice': {'id': '90B', 'name': 'Mammorest Cryst', 'Hp': 150, 'ShotAttack': 85, 'Defense': 90},
    'Yeti': {'id': '91', 'name': 'Wumpo', 'Hp': 140, 'ShotAttack': 80, 'Defense': 100},
    'Yeti_Grass': {'id': '91B', 'name': 'Wumpo Botan', 'Hp': 140, 'ShotAttack': 80, 'Defense': 110},
    'HerculesBeetle': {'id': '92', 'name': 'Warsect', 'Hp': 120, 'ShotAttack': 100, 'Defense': 120},
    'HerculesBeetle_Ground': {'id': '92B', 'name': 'Warsect Terra', 'Hp': 120, 'ShotAttack': 105, 'Defense': 120},
    'FengyunDeeper': {'id': '93', 'name': 'Fenglope', 'Hp': 110, 'ShotAttack': 110, 'Defense': 90},
    'FengyunDeeper_Electric': {'id': '93B', 'name': 'Fenglope Lux', 'Hp': 110, 'ShotAttack': 115, 'Defense': 90},
    'CatVampire': {'id': '94', 'name': 'Felbat', 'Hp': 100, 'ShotAttack': 105, 'Defense': 110},
    'SkyDragon': {'id': '95', 'name': 'Quivern', 'Hp': 105, 'ShotAttack': 100, 'Defense': 100},
    'SkyDragon_Grass': {'id': '95B', 'name': 'Quivern Botan', 'Hp': 105, 'ShotAttack': 105, 'Defense': 100},
    'KingBahamut': {'id': '96', 'name': 'Blazamut', 'Hp': 100, 'ShotAttack': 125, 'Defense': 120},
    'KingBahamut_Dragon': {'id': '96B', 'name': 'Blazamut Ryu', 'Hp': 105, 'ShotAttack': 130, 'Defense': 125},
    'HadesBird': {'id': '97', 'name': 'Helzephyr', 'Hp': 100, 'ShotAttack': 125, 'Defense': 100},
    'HadesBird_Electric': {'id': '97B', 'name': 'Helzephyr Lux', 'Hp': 105, 'ShotAttack': 125, 'Defense': 100},
    'BlackMetalDragon': {'id': '98', 'name': 'Astegon', 'Hp': 100, 'ShotAttack': 125, 'Defense': 125},
    'DarkScorpion': {'id': '99', 'name': 'Menasting', 'Hp': 100, 'ShotAttack': 100, 'Defense': 130},
    'DarkScorpion_Ground': {'id': '99B', 'name': 'Menasting Terra', 'Hp': 100, 'ShotAttack': 105, 'Defense': 130},
    'Anubis': {'id': '100', 'name': 'Anubis', 'Hp': 120, 'ShotAttack': 130, 'Defense': 100},
    'Umihebi': {'id': '101', 'name': 'Jormuntide', 'Hp': 130, 'ShotAttack': 120, 'Defense': 100},
    'Umihebi_Fire': {'id': '101B', 'name': 'Jormuntide Ignis', 'Hp': 130, 'ShotAttack': 130, 'Defense': 100},
    'Suzaku': {'id': '102', 'name': 'Suzaku', 'Hp': 120, 'ShotAttack': 105, 'Defense': 105},
    'Suzaku_Water': {'id': '102B', 'name': 'Suzaku Aqua', 'Hp': 125, 'ShotAttack': 105, 'Defense': 105},
    'ElecPanda': {'id': '103', 'name': 'Grizzbolt', 'Hp': 105, 'ShotAttack': 100, 'Defense': 100},
    'LilyQueen': {'id': '104', 'name': 'Lyleen', 'Hp': 110, 'ShotAttack': 110, 'Defense': 105},
    'LilyQueen_Dark': {'id': '104B', 'name': 'Lyleen Noct', 'Hp': 110, 'ShotAttack': 110, 'Defense': 115},
    'Horus': {'id': '105', 'name': 'Faleris', 'Hp': 100, 'ShotAttack': 105, 'Defense': 110},
    'Horus_Water': {'id': '105B', 'name': 'Faleris Aqua', 'Hp': 100, 'ShotAttack': 110, 'Defense': 110},
    'ThunderDragonMan': {'id': '106', 'name': 'Orserk', 'Hp': 100, 'ShotAttack': 130, 'Defense': 100},
    'BlackGriffon': {'id': '107', 'name': 'Shadowbeak', 'Hp': 120, 'ShotAttack': 120, 'Defense': 140},
    'SaintCentaur': {'id': '108', 'name': 'Paladius', 'Hp': 130, 'ShotAttack': 120, 'Defense': 145},
    'BlackCentaur': {'id': '109', 'name': 'Necromus', 'Hp': 130, 'ShotAttack': 145, 'Defense': 120},
    'IceHorse': {'id': '110', 'name': 'Frostallion', 'Hp': 140, 'ShotAttack': 140, 'Defense': 120},
    'IceHorse_Dark': {'id': '110B', 'name': 'Frostallion Noct', 'Hp': 140, 'ShotAttack': 140, 'Defense': 135},
    'JetDragon': {'id': '111', 'name': 'Jetragon', 'Hp': 110, 'ShotAttack': 140, 'Defense': 110},
    'NightLady': {'id': '112', 'name': 'Bellanoir', 'Hp': 120, 'ShotAttack': 150, 'Defense': 100},
    'NightLady_Dark': {'id': '112B', 'name': 'Bellanoir Libero', 'Hp': 120, 'ShotAttack': 150, 'Defense': 100},
    'MoonQueen': {'id': '113', 'name': 'Selyne', 'Hp': 130, 'ShotAttack': 115, 'Defense': 110},
    'KendoFrog': {'id': '114', 'name': 'Croajiro', 'Hp': 80, 'ShotAttack': 100, 'Defense': 85},
    'KendoFrog_Dark': {'id': '114B', 'name': 'Croajiro Noct', 'Hp': 85, 'ShotAttack': 110, 'Defense': 90},
    'LeafPrincess': {'id': '115', 'name': 'Lullu', 'Hp': 90, 'ShotAttack': 90, 'Defense': 80},
    'MushroomDragon': {'id': '116', 'name': 'Shroomer', 'Hp': 110, 'ShotAttack': 80, 'Defense': 90},
    'MushroomDragon_Dark': {'id': '116B', 'name': 'Shroomer Noct', 'Hp': 110, 'ShotAttack': 85, 'Defense': 90},
    'SmallArmadillo': {'id': '117', 'name': 'Kikit', 'Hp': 75, 'ShotAttack': 70, 'Defense': 90},
    'CandleGhost': {'id': '118', 'name': 'Sootseer', 'Hp': 105, 'ShotAttack': 125, 'Defense': 90},
    'ScorpionMan': {'id': '119', 'name': 'Prixter', 'Hp': 90, 'ShotAttack': 110, 'Defense': 90},
    'WingGolem': {'id': '120', 'name': 'Knocklem', 'Hp': 105, 'ShotAttack': 110, 'Defense': 135},
    'GuardianDog': {'id': '121', 'name': 'Yakumo', 'Hp': 85, 'ShotAttack': 85, 'Defense': 85},
    'SifuDog': {'id': '122', 'name': 'Dogen', 'Hp': 90, 'ShotAttack': 100, 'Defense': 100},
    'FeatherOstrich': {'id': '123', 'name': 'Dazemu', 'Hp': 95, 'ShotAttack': 90, 'Defense': 80},
    'MimicDog': {'id': '124', 'name': 'Mimog', 'Hp': 60, 'ShotAttack': 60, 'Defense': 130},
    'DarkAlien': {'id': '125', 'name': 'Xenovader', 'Hp': 90, 'ShotAttack': 125, 'Defense': 85},
    'WhiteAlienDragon': {'id': '126', 'name': 'Xenogard', 'Hp': 110, 'ShotAttack': 120, 'Defense': 130},
    'DarkMechaDragon': {'id': '127', 'name': 'Xenolord', 'Hp': 130, 'ShotAttack': 120, 'Defense': 120},
    'GhostRabbit': {'id': '128', 'name': 'Nitemary', 'Hp': 105, 'ShotAttack': 95, 'Defense': 105},
    'NightBlueHorse': {'id': '129', 'name': 'Starryon', 'Hp': 110, 'ShotAttack': 100, 'Defense': 100},
    'WhiteShieldDragon': {'id': '130', 'name': 'Silvegis', 'Hp': 120, 'ShotAttack': 110, 'Defense': 115},
    'BlackPuppy': {'id': '131', 'name': 'Smokie', 'Hp': 85, 'ShotAttack': 90, 'Defense': 85},
    'WhiteDeer': {'id': '132', 'name': 'Celesdir', 'Hp': 120, 'ShotAttack': 110, 'Defense': 100},
    'MysteryMask': {'id': '133', 'name': 'Omascul', 'Hp': 95, 'ShotAttack': 105, 'Defense': 100},
    'GrimGirl': {'id': '134', 'name': 'Splatterina', 'Hp': 95, 'ShotAttack': 115, 'Defense': 105},
    'PurpleSpider': {'id': '135', 'name': 'Tarantriss', 'Hp': 110, 'ShotAttack': 100, 'Defense': 100},
    'BlueThunderHorse': {'id': '136', 'name': 'Azurmane', 'Hp': 130, 'ShotAttack': 120, 'Defense': 110},
    'SnowTigerBeastman': {'id': '137', 'name': 'Bastigor', 'Hp': 140, 'ShotAttack': 130, 'Defense': 120},
    'BlueberryFairy': {'id': '138', 'name': 'Prunelia', 'Hp': 105, 'ShotAttack': 95, 'Defense': 100},
    'BadCatgirl': {'id': '139', 'name': 'Nyafia', 'Hp': 110, 'ShotAttack': 100, 'Defense': 100},
    'GoldenHorse': {'id': '140', 'name': 'Gildane', 'Hp': 120, 'ShotAttack': 110, 'Defense': 110},
    'LeafMomonga': {'id': '141', 'name': 'Herbil', 'Hp': 80, 'ShotAttack': 75, 'Defense': 75},
    'IceWitch': {'id': '142', 'name': 'Icelyn', 'Hp': 95, 'ShotAttack': 115, 'Defense': 105},
    'SnowPeafowl': {'id': '143', 'name': 'Frostplume', 'Hp': 110, 'ShotAttack': 100, 'Defense': 100},
    'TropicalOstrich': {'id': '144', 'name': 'Palumba', 'Hp': 105, 'ShotAttack': 110, 'Defense': 115},
    'Plesiosaur': {'id': '145', 'name': 'Braloha', 'Hp': 130, 'ShotAttack': 95, 'Defense': 120},
    'IceCrocodile': {'id': '146', 'name': 'Munchill', 'Hp': 75, 'ShotAttack': 80, 'Defense': 85},
    'IceSeal': {'id': '147', 'name': 'Polapup', 'Hp': 95, 'ShotAttack': 105, 'Defense': 105},
    'TentacleTurtle': {'id': '148', 'name': 'Turtacle', 'Hp': 75, 'ShotAttack': 75, 'Defense': 115},
    'TentacleTurtle_Ground': {'id': '148B', 'name': 'Turtacle Terra', 'Hp': 85, 'ShotAttack': 85, 'Defense': 125},
    'JellyfishGhost': {'id': '149', 'name': 'Jellroy', 'Hp': 90, 'ShotAttack': 75, 'Defense': 75},
    'JellyfishFairy': {'id': '150', 'name': 'Jelliette', 'Hp': 75, 'ShotAttack': 90, 'Defense': 70},
    'OctopusGirl': {'id': '151', 'name': 'Gloopie', 'Hp': 70, 'ShotAttack': 85, 'Defense': 70},
    'StuffedShark': {'id': '152', 'name': 'Finsider', 'Hp': 75, 'ShotAttack': 85, 'Defense': 80},
    'StuffedShark_Fire': {'id': '152B', 'name': 'Finsider Ignis', 'Hp': 75, 'ShotAttack': 90, 'Defense': 80},
    'GhostAnglerfish': {'id': '153', 'name': 'Ghangler', 'Hp': 90, 'ShotAttack': 125, 'Defense': 105},
    'GhostAnglerfish_Fire': {'id': '153B', 'name': 'Ghangler Ignis', 'Hp': 90, 'ShotAttack': 130, 'Defense': 105},
    'IceNarwhal': {'id': '154', 'name': 'Whalaska', 'Hp': 105, 'ShotAttack': 115, 'Defense': 110},
    'IceNarwhal_Fire': {'id': '154B', 'name': 'Whalaska Ignis', 'Hp': 105, 'ShotAttack': 120, 'Defense': 110},
    'PoseidonOrca': {'id': '155', 'name': 'Neptilius', 'Hp': 105, 'ShotAttack': 145, 'Defense': 125},
    'LegendDeer': {'id': '156', 'name': 'Hartalis', 'Hp': 135, 'ShotAttack': 130, 'Defense': 110},
}
