# -*- coding: utf-8 -*-
# ─────────────────────────────────────────────
#  PALWORLD PALS DATABASE  (Give Pal dialog)
#  Source: paldeck.cc/pals
#  (dex, display_name, pal_id, element, emoji)
# ─────────────────────────────────────────────
PW_PALS = [
    # ── Source: paldb.cc/vi/Pals (226 Pal, ID chính xác từ game data) ────────
    # (Tên Hiển Thị, Pal Blueprint ID cho RCON givepal, Element)
    ("001",  "Lamball",            "SheepBall",                  "Neutral",  "🐑"),
    ("002",  "Cattiva",            "PinkCat",                    "Neutral",  "🐱"),
    ("003",  "Chikipi",            "ChickenPal",                 "Neutral",  "🐔"),
    ("004",  "Lifmunk",            "Carbunclo",                  "Grass",    "🐿️"),
    ("005",  "Foxparks",           "Kitsunebi",                  "Fire",     "🦊"),
    ("005B", "Foxparks Cryst",     "Kitsunebi_Ice",              "Ice",      "🦊"),
    ("006",  "Fuack",              "BluePlatypus",               "Water",    "🦆"),
    ("006B", "Fuack Ignis",        "BluePlatypus_Fire",          "Fire",     "🦆"),
    ("007",  "Sparkit",            "ElecCat",                    "Electric", "⚡"),
    ("008",  "Tanzee",             "Monkey",                     "Grass",    "🐒"),
    ("009",  "Rooby",              "FlameBambi",                 "Fire",     "🦌"),
    ("010",  "Pengullet",          "Penguin",                    "Water",    "🐧"),
    ("010B", "Pengullet Lux",      "Penguin_Electric",           "Electric", "🐧"),
    ("011",  "Penking",            "CaptainPenguin",             "Water",    "🐧"),
    ("011B", "Penking Lux",        "CaptainPenguin_Black",       "Electric", "🐧"),
    ("012",  "Jolthog",            "Hedgehog",                   "Electric", "🦔"),
    ("012B", "Jolthog Cryst",      "Hedgehog_Ice",               "Ice",      "🦔"),
    ("013",  "Gumoss",             "PlantSlime",                 "Grass",    "🌿"),
    ("014",  "Vixy",               "CuteFox",                    "Neutral",  "🦊"),
    ("015",  "Hoocrates",          "WizardOwl",                  "Dark",     "🦉"),
    ("016",  "Teafant",            "Ganesha",                    "Water",    "🐘"),
    ("017",  "Depresso",           "NegativeKoala",              "Dark",     "🐨"),
    ("018",  "Cremis",             "WoolFox",                    "Neutral",  "🦊"),
    ("019",  "Daedream",           "DreamDemon",                 "Dark",     "👻"),
    ("020",  "Rushoar",            "Boar",                       "Ground",   "🐗"),
    ("021",  "Nox",                "NightFox",                   "Dark",     "🦊"),
    ("022",  "Fuddler",            "CuteMole",                   "Ground",   "🦔"),
    ("023",  "Killamari",          "NegativeOctopus",            "Dark",     "🐙"),
    ("023B", "Killamari Primo",    "NegativeOctopus_Neutral",    "Neutral",  "🐙"),
    ("024",  "Mau",                "Bastet",                     "Dark",     "🐈"),
    ("024B", "Mau Cryst",          "Bastet_Ice",                 "Ice",      "🐈"),
    ("025",  "Celaray",            "FlyingManta",                "Water",    "🦈"),
    ("025B", "Celaray Lux",        "FlyingManta_Thunder",        "Electric", "🦈"),
    ("026",  "Direhowl",           "Garm",                       "Neutral",  "🐺"),
    ("027",  "Tocotoco",           "ColorfulBird",               "Neutral",  "🐦"),
    ("028",  "Flopie",             "FlowerRabbit",               "Grass",    "🐰"),
    ("029",  "Mozzarina",          "CowPal",                     "Neutral",  "🐄"),
    ("030",  "Bristla",            "LittleBriarRose",            "Grass",    "🌹"),
    ("031",  "Gobfin",             "SharkKid",                   "Water",    "🦈"),
    ("031B", "Gobfin Ignis",       "SharkKid_Fire",              "Fire",     "🦈"),
    ("032",  "Hangyu",             "WindChimes",                 "Ground",   "🎐"),
    ("032B", "Hangyu Cryst",       "WindChimes_Ice",             "Ice",      "🎐"),
    ("033",  "Mossanda",           "GrassPanda",                 "Grass",    "🐼"),
    ("033B", "Mossanda Lux",       "GrassPanda_Electric",        "Electric", "🐼"),
    ("034",  "Woolipop",           "SweetsSheep",                "Neutral",  "🐑"),
    ("035",  "Caprity",            "BerryGoat",                  "Grass",    "🐐"),
    ("035B", "Caprity Noct",       "BerryGoat_Dark",             "Dark",     "🐐"),
    ("036",  "Melpaca",            "Alpaca",                     "Neutral",  "🦙"),
    ("037",  "Eikthyrdeer",        "Deer",                       "Neutral",  "🦌"),
    ("037B", "Eikthyrdeer Terra",  "Deer_Ground",                "Ground",   "🦌"),
    ("038",  "Arsox",              "FlameBuffalo",               "Fire",     "🐃"),
    ("039",  "Dumud",              "LazyCatfish",                "Ground",   "🐟"),
    ("039B", "Dumud Gild",         "LazyCatfish_Gold",           "Ground",   "🐟"),
    ("040",  "Cawgnito",           "DarkCrow",                   "Dark",     "🐦"),
    ("041",  "Leezpunk",           "LizardMan",                  "Dark",     "🦎"),
    ("041B", "Leezpunk Ignis",     "LizardMan_Fire",             "Fire",     "🦎"),
    ("042",  "Loupmoon",           "Werewolf",                   "Dark",     "🐺"),
    ("042B", "Loupmoon Cryst",     "Werewolf_Ice",               "Ice",      "🐺"),
    ("043",  "Galeclaw",           "Eagle",                      "Neutral",  "🦅"),
    ("044",  "Robinquill",         "RobinHood",                  "Grass",    "🏹"),
    ("044B", "Robinquill Terra",   "RobinHood_Ground",           "Ground",   "🏹"),
    ("045",  "Gorirat",            "Gorilla",                    "Neutral",  "🦍"),
    ("045B", "Gorirat Terra",      "Gorilla_Ground",             "Ground",   "🦍"),
    ("046",  "Beegarde",           "SoldierBee",                 "Grass",    "🐝"),
    ("047",  "Elizabee",           "QueenBee",                   "Grass",    "🐝"),
    ("048",  "Grintale",           "NaughtyCat",                 "Neutral",  "🐱"),
    ("049",  "Swee",               "MopBaby",                    "Ice",      "🧹"),
    ("050",  "Sweepa",             "MopKing",                    "Ice",      "🧹"),
    ("051",  "Chillet",            "WeaselDragon",               "Ice",      "🐉"),
    ("051B", "Chillet Ignis",      "WeaselDragon_Fire",          "Fire",     "🐉"),
    ("052",  "Univolt",            "Kirin",                      "Electric", "🦄"),
    ("053",  "Foxcicle",           "IceFox",                     "Ice",      "🦊"),
    ("054",  "Pyrin",              "FireKirin",                  "Fire",     "🐴"),
    ("054B", "Pyrin Noct",         "FireKirin_Dark",             "Dark",     "🐴"),
    ("055",  "Reindrix",           "IceDeer",                    "Ice",      "🦌"),
    ("056",  "Rayhound",           "ThunderDog",                 "Electric", "🐕"),
    ("057",  "Kitsun",             "AmaterasuWolf",              "Fire",     "🦊"),
    ("057B", "Kitsun Noct",        "AmaterasuWolf_Dark",         "Dark",     "🦊"),
    ("058",  "Dazzi",              "RaijinDaughter",             "Electric", "🧚"),
    ("058B", "Dazzi Noct",         "RaijinDaughter_Water",       "Water",    "🧚"),
    ("059",  "Lunaris",            "Mutant",                     "Neutral",  "🌙"),
    ("060",  "Dinossom",           "FlowerDinosaur",             "Grass",    "🦕"),
    ("060B", "Dinossom Lux",       "FlowerDinosaur_Electric",    "Electric", "🦕"),
    ("061",  "Surfent",            "Serpent",                    "Water",    "🐍"),
    ("061B", "Surfent Terra",      "Serpent_Ground",             "Ground",   "🐍"),
    ("062",  "Maraith",            "GhostBeast",                 "Dark",     "👻"),
    ("063",  "Digtoise",           "DrillGame",                  "Ground",   "🐢"),
    ("064",  "Tombat",             "CatBat",                     "Dark",     "🦇"),
    ("065",  "Lovander",           "PinkLizard",                 "Neutral",  "🦎"),
    ("066",  "Flambelle",          "LavaGirl",                   "Fire",     "🔥"),
    ("067",  "Vanwyrm",            "BirdDragon",                 "Dark",     "🐉"),
    ("067B", "Vanwyrm Cryst",      "BirdDragon_Ice",             "Ice",      "🐉"),
    ("068",  "Bushi",              "Ronin",                      "Fire",     "⚔️"),
    ("068B", "Bushi Noct",         "Ronin_Dark",                 "Dark",     "⚔️"),
    ("069",  "Beakon",             "ThunderBird",                "Electric", "🦅"),
    ("070",  "Ragnahawk",          "RedArmorBird",               "Fire",     "🦅"),
    ("071",  "Katress",            "CatMage",                    "Dark",     "🐈"),
    ("071B", "Katress Ignis",      "CatMage_Fire",               "Fire",     "🐈"),
    ("072",  "Wixen",              "FoxMage",                    "Fire",     "🦊"),
    ("072B", "Wixen Noct",         "FoxMage_Dark",               "Dark",     "🦊"),
    ("073",  "Verdash",            "GrassRabbitMan",             "Grass",    "🐰"),
    ("074",  "Vaelet",             "VioletFairy",                "Grass",    "🧚"),
    ("075",  "Sibelyx",            "WhiteMoth",                  "Ice",      "🦋"),
    ("076",  "Elphidran",          "FairyDragon",                "Dragon",   "🐉"),
    ("076B", "Elphidran Aqua",     "FairyDragon_Water",          "Water",    "🐉"),
    ("077",  "Kelpsea",            "Kelpie",                     "Water",    "🐟"),
    ("077B", "Kelpsea Ignis",      "Kelpie_Fire",                "Fire",     "🐟"),
    ("078",  "Azurobe",            "BlueDragon",                 "Water",    "🐉"),
    ("078B", "Azurobe Cryst",      "BlueDragon_Ice",             "Ice",      "🐉"),
    ("079",  "Cryolinx",           "WhiteTiger",                 "Ice",      "🐅"),
    ("079B", "Cryolinx Terra",     "WhiteTiger_Ground",          "Ground",   "🐅"),
    ("080",  "Blazehowl",          "Manticore",                  "Fire",     "🦁"),
    ("080B", "Blazehowl Noct",     "Manticore_Dark",             "Dark",     "🦁"),
    ("081",  "Relaxaurus",         "LazyDragon",                 "Dragon",   "🦕"),
    ("081B", "Relaxaurus Lux",     "LazyDragon_Electric",        "Electric", "🦕"),
    ("082",  "Broncherry",         "SakuraSaurus",               "Grass",    "🌸"),
    ("082B", "Broncherry Aqua",    "SakuraSaurus_Water",         "Water",    "🌸"),
    ("083",  "Petallia",           "FlowerDoll",                 "Grass",    "🌺"),
    ("084",  "Reptyro",            "VolcanicMonster",            "Fire",     "🦎"),
    ("084B", "Reptyro Cryst",      "VolcanicMonster_Ice",        "Ice",      "🦎"),
    ("085",  "Kingpaca",           "KingAlpaca",                 "Neutral",  "🦙"),
    ("085B", "Kingpaca Cryst",     "KingAlpaca_Ice",             "Ice",      "🦙"),
    ("086",  "Mammorest",          "GrassMammoth",               "Grass",    "🦣"),
    ("086B", "Mammorest Cryst",    "GrassMammoth_Ice",           "Ice",      "🦣"),
    ("087",  "Wumpo",              "Yeti",                       "Ice",      "🗿"),
    ("087B", "Wumpo Botan",        "Yeti_Grass",                 "Grass",    "🗿"),
    ("088",  "Warsect",            "HerculesBeetle",             "Grass",    "🦗"),
    ("088B", "Warsect Terra",      "HerculesBeetle_Ground",      "Ground",   "🦗"),
    ("089",  "Fenglope",           "FengyunDeeper",              "Neutral",  "🦌"),
    ("089B", "Fenglope Lux",       "FengyunDeeper_Electric",     "Electric", "⚡"),
    ("090",  "Felbat",             "CatVampire",                 "Dark",     "🦇"),
    ("091",  "Quivern",            "SkyDragon",                  "Dragon",   "🐉"),
    ("091B", "Quivern Botan",      "SkyDragon_Grass",            "Grass",    "🐉"),
    ("092",  "Blazamut",           "KingBahamut",                "Fire",     "🦎"),
    ("092B", "Blazamut Ryu",       "KingBahamut_Dragon",         "Dragon",   "🦎"),
    ("093",  "Helzephyr",          "HadesBird",                  "Dark",     "🐉"),
    ("093B", "Helzephyr Lux",      "HadesBird_Electric",         "Electric", "🐉"),
    ("094",  "Astegon",            "BlackMetalDragon",           "Dragon",   "🐉"),
    ("095",  "Menasting",          "DarkScorpion",               "Dark",     "🦂"),
    ("095B", "Menasting Terra",    "DarkScorpion_Ground",        "Ground",   "🦂"),
    ("096",  "Anubis",             "Anubis",                     "Ground",   "🐺"),
    ("097",  "Jormuntide",         "Umihebi",                    "Water",    "🐍"),
    ("097B", "Jormuntide Ignis",   "Umihebi_Fire",               "Fire",     "🐍"),
    ("098",  "Suzaku",             "Suzaku",                     "Fire",     "🐦"),
    ("098B", "Suzaku Aqua",        "Suzaku_Water",               "Water",    "🐦"),
    ("099",  "Grizzbolt",          "ElecPanda",                  "Electric", "🐻"),
    ("100",  "Lyleen",             "LilyQueen",                  "Grass",    "🌺"),
    ("100B", "Lyleen Noct",        "LilyQueen_Dark",             "Dark",     "🌺"),
    ("101",  "Faleris",            "Horus",                      "Fire",     "🦅"),
    ("101B", "Faleris Aqua",       "Horus_Water",                "Water",    "🦅"),
    ("102",  "Orserk",             "ThunderDragonMan",           "Electric", "🐉"),
    ("103",  "Shadowbeak",         "BlackGriffon",               "Dark",     "🐦"),
    ("104",  "Paladius",           "SaintCentaur",               "Neutral",  "🦄"),
    ("105",  "Necromus",           "BlackCentaur",               "Dark",     "🐴"),
    ("106",  "Frostallion",        "IceHorse",                   "Ice",      "🦄"),
    ("106B", "Frostallion Noct",   "IceHorse_Dark",              "Dark",     "🦄"),
    ("107",  "Jetragon",           "JetDragon",                  "Dragon",   "🐉"),
    ("108",  "Bellanoir",          "NightLady",                  "Dark",     "👹"),
    ("108B", "Bellanoir Libero",   "NightLady_Dark",             "Dark",     "👹"),
    ("109",  "Selyne",             "MoonQueen",                  "Dark",     "🌙"),
    ("110",  "Croajiro",           "KendoFrog",                  "Water",    "🐸"),
    ("110B", "Croajiro Noct",      "KendoFrog_Dark",             "Dark",     "🐸"),
    ("111",  "Lullu",              "LeafPrincess",               "Grass",    "🌿"),
    ("112",  "Shroomer",           "MushroomDragon",             "Neutral",  "🍄"),
    ("112B", "Shroomer Noct",      "MushroomDragon_Dark",        "Dark",     "🍄"),
    ("113",  "Kikit",              "SmallArmadillo",             "Neutral",  "🦔"),
    ("114",  "Sootseer",           "CandleGhost",                "Dark",     "👻"),
    ("115",  "Prixter",            "ScorpionMan",                "Ground",   "🦂"),
    ("116",  "Knocklem",           "WingGolem",                  "Ground",   "🗿"),
    ("117",  "Yakumo",             "GuardianDog",                "Neutral",  "🐕"),
    ("118",  "Dogen",              "SifuDog",                    "Neutral",  "🐕"),
    ("119",  "Dazemu",             "FeatherOstrich",             "Neutral",  "🐦"),
    ("120",  "Mimog",              "MimicDog",                   "Dark",     "🐕"),
    ("121",  "Xenovader",          "DarkAlien",                  "Dark",     "👽"),
    ("122",  "Xenogard",           "WhiteAlienDragon",           "Neutral",  "🐉"),
    ("123",  "Xenolord",           "DarkMechaDragon",            "Dark",     "🐉"),
    ("124",  "Nitemary",           "GhostRabbit",                "Dark",     "🐰"),
    ("125",  "Starryon",           "NightBlueHorse",             "Dark",     "🐴"),
    ("126",  "Silvegis",           "WhiteShieldDragon",          "Neutral",  "🐉"),
    ("127",  "Smokie",             "BlackPuppy",                 "Dark",     "🐕"),
    ("128",  "Celestedir",         "WhiteDeer",                  "Neutral",  "🦌"),
    ("129",  "Omascul",            "MysteryMask",                "Neutral",  "🎭"),
    ("130",  "Splatterina",        "GrimGirl",                   "Dark",     "👻"),
    ("131",  "Tarantris",          "PurpleSpider",               "Dark",     "🕷️"),
    ("132",  "Azurmane",           "BlueThunderHorse",           "Electric", "🐴"),
    ("133",  "Bastigor",           "SnowTigerBeastman",          "Ice",      "🐅"),
    ("134",  "Prunelia",           "BlueberryFairy",             "Grass",    "🧚"),
    ("135",  "Nyafia",             "BadCatgirl",                 "Dark",     "🐱"),
    ("136",  "Gildane",            "GoldenHorse",                "Neutral",  "🐴"),
    ("137",  "Herbil",             "LeafMomonga",                "Grass",    "🐿️"),
    ("138",  "Icelyn",             "IceWitch",                   "Ice",      "🧙"),
    ("139",  "Frostplume",         "SnowPeafowl",                "Ice",      "🦚"),
    ("140",  "Palumba",            "TropicalOstrich",            "Neutral",  "🐦"),
    ("141",  "Braloha",            "Plesiosaur",                 "Water",    "🦕"),
    ("142",  "Munchill",           "IceCrocodile",               "Ice",      "🐊"),
    ("143",  "Polapup",            "IceSeal",                    "Ice",      "🦭"),
    ("144",  "Turtacle",           "TentacleTurtle",             "Water",    "🐢"),
    ("144B", "Turtacle Terra",     "TentacleTurtle_Ground",      "Ground",   "🐢"),
    ("145",  "Jellroy",            "JellyfishGhost",             "Water",    "🪼"),
    ("146",  "Jelliette",          "JellyfishFairy",             "Water",    "🪼"),
    ("147",  "Gloopie",            "OctopusGirl",                "Water",    "🐙"),
    ("148",  "Finsider",           "StuffedShark",               "Water",    "🦈"),
    ("148B", "Finsider Ignis",     "StuffedShark_Fire",          "Fire",     "🦈"),
    ("149",  "Ghangler",           "GhostAnglerfish",            "Dark",     "🐟"),
    ("149B", "Ghangler Ignis",     "GhostAnglerfish_Fire",       "Fire",     "🐟"),
    ("150",  "Whalaska",           "IceNarwhal",                 "Ice",      "🐳"),
    ("150B", "Whalaska Ignis",     "IceNarwhal_Fire",            "Fire",     "🐳"),
    ("151",  "Neptillius",         "PoseidonOrca",               "Water",    "🐬"),
    ("152",  "Hartalis",           "LegendDeer",                 "Neutral",  "🦌"),
    ("★",   "Slime Xanh Lá",      "YakushimaMonster001",         "Grass",    "🟢"),
    ("★",   "Nitewing",            "HawkBird",                   "Neutral",  "🦅"),
    ("★",   "Ribbuny",             "PinkRabbit",                 "Neutral",  "🐰"),
    ("★",   "Ribbuny Botan",       "PinkRabbit_Grass",           "Grass",    "🐰"),
    ("★",   "Cinnamoth",           "CuteButterfly",              "Ice",      "🦋"),
    ("★",   "Incineram",           "Baphomet",                   "Fire",     "🦊"),
    ("★",   "Incineram Noct",      "Baphomet_Dark",              "Dark",     "🦊"),
]
